version: '3.5'
services:
 nginx:
  networks:
   - inception_network
  image: nginx
  restart: always
  depends_on:
   - wordpress
   - mariadb
  container_name: nginx
  build: ./requirements/nginx/
  ports:
   - 443:443
  volumes:
   - myapp:/var/www/html
 
 mariadb:
  networks:
   - inception_network
  image: mariadb
  container_name: mariadb
  build: ./requirements/mariadb/
  ports:
   - 3306:3306
  volumes:
   - db:/var/lib/mysql
  env_file:
   - .env

 wordpress:
  networks:
   - inception_network
  image: wordpress
  restart: always
  container_name: wordpress
  depends_on:
   - mariadb
  ports:
   - 9000:9000
  build: ./requirements/wordpress/
  volumes:
   - myapp:/var/www/html/
  env_file:
   - .env
   
 adminer:
    networks:
      - inception_network
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - 8080:80
    build: ./requirements/bonus/adminer/
    env_file:
      - .env
 redis:
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception_network
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis/
    ports:
      - 6379:6379
 website:
    restart: always
    networks:
      - inception_network
    image: website
    build: ./requirements/bonus/website/
    container_name: website
    ports:
      - 3000:3000


volumes:
 myapp:
  driver: local
  driver_opts:
   type: 'none'
   o: bind
   device: /home/abdait-m/data/wp
  #  device: /Users/abdait-m/data/wp
 db:
  driver: local
  driver_opts:
   type: 'none'
   o: bind
   device: /home/abdait-m/data/db
  #  device: /Users/abdait-m/data/db


networks:
 inception_network:
  name: 'inception_network'
  driver: bridge